[server]
listen_host = "127.0.0.1"
listen_port = 8765

[services.web-reader]
upstream_url = "https://open.bigmodel.cn/api/mcp/web_reader/mcp"
# service supports 2024-11-05
# codex expects 2025-06-18
# proxy will downgrade request and rewrite response

[services.web-search-prime]
upstream_url = "https://open.bigmodel.cn/api/mcp/web_search_prime/mcp"

[services.zread]
upstream_url = "https://open.bigmodel.cn/api/mcp/zread/mcp"
